# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    args: [
            '--bucket=gs://${_CACHE_BUCKET}',
            '--key=maven-$(find -name pom.xml -exec cksum {} \; | cksum | cut -d " " -f1)',
            '--key_fallback=maven-' ]
  - name: 'maven:3-jdk-8-alpine'
    entrypoint: 'mvn'
    # parallel builds (-T2) hang for some reason
    args: [
            'package', '--batch-mode', '--errors', '--fail-at-end',
            '--show-version', '-DinstallAtEnd=true', '-DdeployAtEnd=true', '-DskipTests',
            '-Dmaven.repo.local=/workspace/.m2/repository',
            '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN',
            '-Djava.awt.headless=true', '-Dhttps.protocols=TLSv1.2'
          ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '--build-arg', 'SERVICE_NAME=${_SERVICE_NAME}',
            '-t', 'gcr.io/$PROJECT_ID/osdu-gcp-${_SERVICE_NAME}:${_SHORT_SHA}',
            '-t', 'gcr.io/$PROJECT_ID/osdu-gcp-${_SERVICE_NAME}:latest',
            '-f', 'Dockerfile.cloudbuild',
            '.' ]
  - name: 'gcr.io/$PROJECT_ID/save_cache'
    args: [
            '--bucket=gs://${_CACHE_BUCKET}',
            '--key=maven-$(find -name pom.xml -exec cksum {} \; | cksum | cut -d " " -f1)',
            '--path=.m2/repository',
            '--no-clobber' ]
images:
  - 'gcr.io/$PROJECT_ID/osdu-gcp-${_SERVICE_NAME}'
