# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software§
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

git:
  folder:
    path: resources/git
osdu:
  delfi:
    portal:
      appkey: ${osdu.delfi.portal.appKey}
      url: ${osdu.delfi.portal.url}
search:
  delfi:
    client:
      appKeyHeader: AppKey
      authorizationHeader: Authorization
      partitionHeader: slb-data-partition-id
      serverUrl: ${search.delfi.client.serverUrl}
  mapper:
    searchEndpoint: de/search/v2/query

