# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
osdu:
  delfi:
    filePortal:
      url: ${osdu.delfi.filePortal.url}
    portal:
      appkey: ${osdu.delfi.portal.appKey}
      url: ${osdu.delfi.portal.url}
  ingest:
    submit:
      pollingInterval: 1000
      pollingCycles: 180
gcp:
  storage:
    tempLocationBucket: ${gcp.storage.tempLocationBucket}
